(() => {
  "use strict";
  let client;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  async function getClient(){if(window.PopitaiSupabase)return window.PopitaiSupabase;return new Promise(r=>{const t=setInterval(()=>{if(window.PopitaiSupabase){clearInterval(t);r(window.PopitaiSupabase)}},50)})}
  async function allowed(){client=client||await getClient();const {data:u}=await client.auth.getUser();if(!u?.user)return false;const {data:p}=await client.from("profiles").select("role,is_blocked").eq("id",u.user.id).maybeSingle();return p?.role==="admin"&&p?.is_blocked!==true}
  function ensureButton(){const menu=document.querySelector(".admin-menu");if(!menu||menu.querySelector("[data-info-admin]"))return;const b=document.createElement("button");b.type="button";b.dataset.infoAdmin="1";b.textContent="Инфо Лом";b.addEventListener("click",open);menu.appendChild(b)}
  async function open(){if(!(await allowed()))return;const menu=document.querySelector(".admin-menu"),box=document.querySelector(".admin-content");menu?.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.infoAdmin==="1"));if(!box)return;box.innerHTML='<div class="block-heading"><h2>Инфо Лом</h2></div><div class="stack-list"><article class="empty-card"><p>Зареждане…</p></article></div>';
    const [e,s,r]=await Promise.all([client.from("info_entries").select("id,category,subcategory,name,publication_status,reliability_status,confirmed_at").order("category").order("name"),client.from("info_submissions").select("id,category,subcategory,entry_type,data,status,created_at").eq("status","pending").order("created_at",{ascending:false}),client.from("info_error_reports").select("id,category,subcategory,description,status,created_at").eq("status","pending").order("created_at",{ascending:false})]);
    const entries=e.data||[],subs=s.data||[],reports=r.data||[];
    box.innerHTML=`<div class="block-heading"><h2>Инфо Лом</h2></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px"><button type="button" data-tab="entries">Записи (${entries.length})</button><button type="button" data-tab="subs">Предложения (${subs.length})</button><button type="button" data-tab="reports">Сигнали (${reports.length})</button><a href="info.html" target="_blank">Виж страницата</a></div><div id="info-admin-list"></div>`;
    const draw=tab=>{const out=document.getElementById("info-admin-list");if(!out)return;if(tab==="entries")out.innerHTML=`<div class="stack-list">${entries.map(x=>`<article class="admin-item-card"><strong>${esc(x.name)}</strong><p>${esc(x.category)} · ${esc(x.subcategory||"")}</p><p>${esc(x.publication_status)} · ${esc(x.reliability_status)}</p></article>`).join("")||'<article class="empty-card"><p>Няма записи.</p></article>'}</div>`;else if(tab==="subs")out.innerHTML=`<div class="stack-list">${subs.map(x=>`<article class="admin-item-card"><strong>${esc(x.data?.name||"Предложение")}</strong><p>${esc(x.category)} · ${esc(x.subcategory||"")}</p><p>${esc(x.data?.details||"")}</p></article>`).join("")||'<article class="empty-card"><p>Няма чакащи предложения.</p></article>'}</div>`;else out.innerHTML=`<div class="stack-list">${reports.map(x=>`<article class="admin-item-card"><strong>Сигнал за грешка</strong><p>${esc(x.category||"")} · ${esc(x.subcategory||"")}</p><p>${esc(x.description)}</p></article>`).join("")||'<article class="empty-card"><p>Няма чакащи сигнали.</p></article>'}</div>`};
    box.querySelectorAll("[data-tab]").forEach(b=>b.addEventListener("click",()=>draw(b.dataset.tab)));draw(subs.length?"subs":reports.length?"reports":"entries")}
  document.addEventListener("DOMContentLoaded",async()=>{if(!(await allowed()))return;ensureButton();const m=document.querySelector(".admin-menu");if(m)new MutationObserver(ensureButton).observe(m,{childList:true})});
})();