"use strict";
  function validatePhone(v){const s=String(v||"").trim();if(!s)return "Въведи телефон.";if(/\p{L}/u.test(s))return "Телефонът не може да съдържа букви.";if(!/^[+\d\s().-]+$/.test(s))return "Използвай само цифри, интервали, +, тирета или скоби.";const digits=s.replace(/\D/g,"");if(s.startsWith("+")){if(!s.startsWith("+359"))return "Българският международен номер трябва да започва с +359.";if(![11,12].includes(digits.length))return "След +359 трябва да има 8 или 9 цифри.";}else{if(!digits.startsWith("0"))return "Номерът трябва да започва с 0 или +359.";if(![9,10].includes(digits.length))return "Телефонът трябва да съдържа общо 9 или 10 цифри.";}return ""}
  function setFieldError(el,msg){const box=el.closest(".field")||el.closest("fieldset");if(box)box.classList.toggle("invalid",Boolean(msg));const form=el.form;const key=el.name;const err=form?.querySelector(`[data-error-for="${CSS.escape(key)}"]`);if(err)err.textContent=msg||"";el.setAttribute("aria-invalid",msg?"true":"false")}
  function validateControl(el){if(!el.name||el.type==="hidden"||el.disabled)return true;let msg="";const v=el.type==="checkbox"||el.type==="radio"?"":el.value.trim();if(el.required){if(el.type==="checkbox"&&!el.checked)msg="Това потвърждение е задължително.";else if(el.type==="radio"&&!el.form.querySelector(`[name="${CSS.escape(el.name)}"]:checked`))msg="Избери една от опциите.";else if(!["checkbox","radio"].includes(el.type)&&!v)msg="Полето е задължително."}if(!msg&&v&&el.minLength>0&&v.length<el.minLength)msg=`Въведи поне ${el.minLength} знака.`;if(!msg&&v&&el.maxLength>0&&v.length>el.maxLength)msg=`Максимум ${el.maxLength} знака.`;if(!msg&&el.type==="email"&&v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))msg="Въведи валиден имейл адрес.";if(!msg&&el.type==="tel"&&v)msg=validatePhone(v);setFieldError(el,msg);return !msg}
  function validateForm(form){const controls=[...form.elements].filter(el=>el.name&&!el.disabled);let first=null;controls.forEach(el=>{if(!validateControl(el)&&!first)first=el});if(form.dataset.form==="register"){const p=form.elements.password,c=form.elements.confirm_password;if(p&&c&&p.value!==c.value){setFieldError(c,"Паролите не съвпадат.");first=first||c}}if(first){first.focus();first.scrollIntoView({behavior:"smooth",block:"center"});return false}return true}
  function bindFormUX(){document.querySelectorAll(".proto-form").forEach(form=>{if(form.dataset.bound)return;form.dataset.bound="1";form.addEventListener("input",e=>{if(e.target.matches("input,select,textarea")){state.dirty=true;if(e.target.dataset.touched)validateControl(e.target)}});form.addEventListener("focusout",e=>{if(e.target.matches("input,select,textarea")&&e.target.name){e.target.dataset.touched="1";validateControl(e.target)}})});const photos=document.getElementById("listing-photos");if(photos&&!photos.dataset.bound){photos.dataset.bound="1";photos.addEventListener("change",()=>{const files=[...photos.files].slice(0,6),box=document.getElementById("listing-photo-preview");if(box)box.innerHTML=files.map((f,i)=>`<span>${esc(f.name.slice(0,10))}${f.name.length>10?"…":""}</span>`).join("");if(photos.files.length>6)toast("За normal flow се показват максимум 6 снимки.")})}}
  function bindDuplicateCheck(){const input=document.querySelector('[data-form="question"] [name="title"]'),warn=document.getElementById("duplicate-warning"),copy=document.getElementById("duplicate-copy"),open=document.getElementById("open-duplicate");if(!input||!warn)return;const check=()=>{const words=input.value.toLocaleLowerCase("bg-BG").split(/\s+/).filter(x=>x.length>4);const hit=D.questions.find(q=>words.filter(w=>q.title.toLocaleLowerCase("bg-BG").includes(w)).length>=2);warn.hidden=!hit;if(hit){copy.textContent=` Подобен въпрос: „${hit.title}“`;open.dataset.route=`question/${hit.id}`}};input.addEventListener("blur",check);check()}
  function requireSignIn(formType){if(signedIn())return true;state.dirty=false;toast("За изпращане е нужен вход. Данните остават само в прототипа.");navigate(`auth/login?source=${encodeURIComponent(formType)}`,{force:true});return false}
  function successScreen(title,text,nextRoute="home",nextLabel="Към началото",shareNote=false){state.dirty=false;main.innerHTML=pageIntro("Готово",title,text)+`<section class="section"><div class="shell form-wrap"><div class="form-card"><div class="notice notice-ok"><strong>${esc(title)}</strong>${esc(text)}</div>${shareNote?`<div class="notice notice-info mt-12"><strong>Facebook / споделяне</strong>След одобрение и публичен canonical URL бутонът „Сподели“ става активен. Pending съдържание не се рекламира като публично.</div>`:""}<div class="form-actions mt-16"><button class="button button-primary" data-route="${esc(nextRoute)}">${esc(nextLabel)}</button><button class="button button-soft" data-route="profile">Виж профила / статуса</button></div></div></div></section>`;window.scrollTo({top:0,behavior:"smooth"})}
  function submitForm(form){if(!validateForm(form))return;const type=form.dataset.form,fd=new FormData(form);if(["listing","firm","health-proposal","shop-proposal","question","answer","correction","report","offer-request"].includes(type)&&!requireSignIn(type))return;state.dirty=false;
    if(type==="home-search"||type==="search"){navigate(`search?q=${encodeURIComponent(fd.get("q")||"")}`,{force:true});return}
    if(type==="login"){state.role="user";saveState();successScreen("Входът е успешен","В прототипа си влязъл като обикновен потребител.","profile","Към профила");refreshRoleUI();return}
    if(type==="register"){state.role="user";saveState();successScreen("Профилът е създаден","Симулация: акаунтът е активен и си влязъл.","profile","Към профила");refreshRoleUI();return}
    if(type==="recover"){successScreen("Инструкциите са изпратени","Симулация: провери електронната си поща за линк за възстановяване.","auth/login","Към вход");return}
    if(type==="listing"){const edit=Boolean(form.dataset.editId);state.submissions.push({kind:"listing",status:isAdmin()?"approved":"pending",time:Date.now()});saveState();if(isAdmin())successScreen(edit?"Промените са публикувани":"Обявата е публикувана","Admin direct-publish behavior е симулиран според protected rules.","marketplace","Към обявите");else successScreen(edit?"Промените са изпратени за преглед":"Изпратено за преглед",edit?"Редакцията чака одобрение; последната одобрена версия остава публична.":"Обявата няма да е публична преди одобрение.","marketplace","Към обявите",true);return}
    if(type==="firm"){const edit=Boolean(form.dataset.editId);state.submissions.push({kind:"firm",status:isAdmin()?"approved":"pending",time:Date.now()});saveState();successScreen(isAdmin()?(edit?"Фирмата е обновена и публикувана":"Фирмата е публикувана"):(edit?"Редакцията е изпратена за преглед":"Фирмата е изпратена за преглед"),isAdmin()?"Admin direct-publish behavior е симулиран.":"Последната одобрена версия остава публична до одобряване на промяната.","firms","Към фирмите",!isAdmin());return}
    if(type==="health-proposal"){successScreen("Изпратено е за одобрение","Ще се публикува само след преглед.","marketplace/services?group=health","Към Здраве и грижа",true);return}
    if(type==="shop-proposal"){successScreen("Предложението е изпратено за проверка","Магазинът няма да се показва публично преди одобрение.","shops","Към магазините",true);return}
    if(type==="question"){successScreen(isAdmin()?"Въпросът е публикуван":"Въпросът е изпратен за преглед",isAdmin()?"Admin direct publish е симулиран според съществуващия owner.":"След одобрение въпросът ще има публичен canonical URL.","questions","Към въпросите",!isAdmin());return}
    if(type==="answer"){successScreen("Отговорът е изпратен за преглед","Ще се появи публично само след одобрение.",`question/${form.dataset.questionId}`,"Към въпроса");return}
    if(type==="correction"){successScreen("Корекцията е изпратена","Публичният Info/Health запис не е променен директно. Предложението чака проверка.","info","Към Инфо Лом");return}
    if(type==="report"){successScreen("Сигналът е изпратен","Съдържанието не се изтрива автоматично; сигналът влиза в moderation flow.","home","Към началото");return}
    if(type==="offer-request"){successScreen("Запитването е подготвено","В прототипа няма реално изпращане. Финалният owner/доставка ще се заключи преди production implementation.","firms","Към фирмите");return}
    if(type==="contact"){successScreen("Съобщението е прието","Това е симулация на контактната форма в прототипа.","home","Към началото");return}
  }
