"use strict";
  const PROTO_DRAFT_KEY="popitai_v6_r1_pending_draft";
  function validatePhone(v){const s=String(v||"").trim();if(!s)return "Въведи телефон.";if(/\p{L}/u.test(s))return "Телефонът не може да съдържа букви.";if(!/^[+\d\s().-]+$/.test(s))return "Използвай само цифри, интервали, +, тирета или скоби.";const digits=s.replace(/\D/g,"");if(s.startsWith("+")){if(!s.startsWith("+359"))return "Българският международен номер трябва да започва с +359.";if(![11,12].includes(digits.length))return "След +359 трябва да има 8 или 9 цифри.";}else{if(!digits.startsWith("0"))return "Номерът трябва да започва с 0 или +359.";if(![9,10].includes(digits.length))return "Телефонът трябва да съдържа общо 9 или 10 цифри.";}return ""}
  function setFieldError(el,msg){const box=el.closest(".field")||el.closest("fieldset");if(box)box.classList.toggle("invalid",Boolean(msg));const form=el.form;const key=el.name;const err=form?.querySelector(`[data-error-for="${CSS.escape(key)}"]`);if(err)err.textContent=msg||"";el.setAttribute("aria-invalid",msg?"true":"false")}
  function validateControl(el){if(!el.name||el.type==="hidden"||el.disabled)return true;let msg="";const v=el.type==="checkbox"||el.type==="radio"?"":el.value.trim();if(el.required){if(el.type==="checkbox"&&!el.checked)msg="Това потвърждение е задължително.";else if(el.type==="radio"&&!el.form.querySelector(`[name="${CSS.escape(el.name)}"]:checked`))msg="Избери една от опциите.";else if(!["checkbox","radio"].includes(el.type)&&!v)msg="Полето е задължително."}if(!msg&&v&&el.minLength>0&&v.length<el.minLength)msg=`Въведи поне ${el.minLength} знака.`;if(!msg&&v&&el.maxLength>0&&v.length>el.maxLength)msg=`Максимум ${el.maxLength} знака.`;if(!msg&&el.type==="email"&&v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))msg="Въведи валиден имейл адрес.";if(!msg&&el.type==="tel"&&v)msg=validatePhone(v);setFieldError(el,msg);return !msg}
  function validateForm(form){const controls=[...form.elements].filter(el=>el.name&&!el.disabled);let first=null;controls.forEach(el=>{if(!validateControl(el)&&!first)first=el});if(form.dataset.form==="register"){const p=form.elements.password,c=form.elements.confirm_password;if(p&&c&&p.value!==c.value){setFieldError(c,"Паролите не съвпадат.");first=first||c}}if(first){first.focus();first.scrollIntoView({behavior:"smooth",block:"center"});return false}return true}
  function syncListingIntentType(form){if(form?.dataset.form!=="listing")return;const select=form.elements.listing_type;if(!select)return;const mainValue=form.elements.main?.value||"",intent=form.querySelector('[name="intent"]:checked')?.value||"";if(!intent){select.innerHTML='<option value="">Първо избери „Предлагам“ или „Търся“</option>';select.disabled=true;return}select.disabled=false;let allowed=null;if(mainValue==="work")allowed=intent==="seek"?["Търси работа"]:["Предлага работа"];else if(mainValue==="property")allowed=intent==="seek"?["Търси под наем","Търси за купуване"]:["Продава имот","Отдава под наем"];if(!allowed)return;const current=allowed.includes(select.value)?select.value:allowed[0];select.innerHTML=allowed.map(v=>`<option value="${esc(v)}" ${v===current?"selected":""}>${esc(v)}</option>`).join("")}
  function snapshotForm(form,formType){const values=[];[...form.elements].forEach(el=>{if(!el.name||el.disabled||el.type==="file"||el.type==="password"||el.type==="submit"||el.type==="button")return;if(el.type==="radio"||el.type==="checkbox")values.push({name:el.name,type:el.type,value:el.value,checked:el.checked});else values.push({name:el.name,type:el.type,value:el.value})});const draft={formType,route:routeInfo().raw,values};try{sessionStorage.setItem(PROTO_DRAFT_KEY,JSON.stringify(draft))}catch{}return draft}
  function readPendingDraft(){try{return JSON.parse(sessionStorage.getItem(PROTO_DRAFT_KEY)||"null")}catch{return null}}
  function clearPendingDraft(){try{sessionStorage.removeItem(PROTO_DRAFT_KEY)}catch{}}
  function draftValue(draft,name){const row=draft?.values?.find(x=>x.name===name&&(x.type!=="radio"||x.checked));return row?.value||""}
  function restorePendingDraft(){const draft=readPendingDraft();if(!draft||draft.route!==routeInfo().raw)return false;const form=document.querySelector(`form[data-form="${CSS.escape(draft.formType)}"]`);if(!form)return false;if(form.dataset.form==="listing"){const mainValue=draftValue(draft,"main"),groupValue=draftValue(draft,"service_group"),leafValue=draftValue(draft,"leaf"),typeValue=draftValue(draft,"listing_type");draft.values.filter(x=>x.name==="intent"&&x.checked).forEach(x=>{const el=form.querySelector(`[name="intent"][value="${CSS.escape(x.value)}"]`);if(el)el.checked=true});if(form.elements.main)form.elements.main.value=mainValue;updateListingContext(mainValue,groupValue,leafValue,typeValue)}draft.values.forEach(x=>{const matches=[...form.querySelectorAll(`[name="${CSS.escape(x.name)}"]`)];matches.forEach(el=>{if(el.type==="radio"||el.type==="checkbox")el.checked=Boolean(x.checked&&el.value===x.value);else el.value=x.value})});syncListingIntentType(form);state.dirty=true;toast("Входът е успешен. Попълненото е възстановено.");return true}
  function bindFormUX(){document.querySelectorAll(".proto-form").forEach(form=>{if(!form.dataset.bound){form.dataset.bound="1";form.addEventListener("input",e=>{if(e.target.matches("input,select,textarea")){state.dirty=true;if(e.target.dataset.touched)validateControl(e.target)}});form.addEventListener("focusout",e=>{if(e.target.matches("input,select,textarea")&&e.target.name){e.target.dataset.touched="1";validateControl(e.target)}})}if(form.dataset.form==="listing"){syncListingIntentType(form);if(!form.dataset.listingDynamicBound){form.dataset.listingDynamicBound="1";form.addEventListener("change",e=>{if(!["main","service_group","leaf","intent"].includes(e.target.name))return;const mainValue=form.elements.main?.value||"",groupValue=form.elements.service_group?.value||"",leafValue=form.elements.leaf?.value||"",typeValue=form.elements.listing_type?.value||"";updateListingContext(mainValue,groupValue,leafValue,typeValue);syncListingIntentType(form)})}}});const photos=document.getElementById("listing-photos");if(photos&&!photos.dataset.bound){photos.dataset.bound="1";photos.addEventListener("change",()=>{const files=[...photos.files].slice(0,6),box=document.getElementById("listing-photo-preview");if(box)box.innerHTML=files.map(f=>`<span>${esc(f.name.slice(0,10))}${f.name.length>10?"…":""}</span>`).join("");if(photos.files.length>6)toast("За обикновен профил се показват максимум 6 снимки.")})}}
  function bindDuplicateCheck(){const input=document.querySelector('[data-form="question"] [name="title"]'),warn=document.getElementById("duplicate-warning"),copy=document.getElementById("duplicate-copy"),open=document.getElementById("open-duplicate");if(!input||!warn)return;const check=()=>{const words=input.value.toLocaleLowerCase("bg-BG").split(/\s+/).filter(x=>x.length>4);const hit=D.questions.find(q=>words.filter(w=>q.title.toLocaleLowerCase("bg-BG").includes(w)).length>=2);warn.hidden=!hit;if(hit){copy.textContent=` Подобен въпрос: „${hit.title}“`;open.dataset.route=`question/${hit.id}`}};input.addEventListener("blur",check);check()}
  function requireSignIn(formType,form){if(signedIn())return true;snapshotForm(form,formType);state.dirty=false;toast("За изпращане е нужен вход. Попълненото ще бъде възстановено след вход.");navigate(`auth/login?source=${encodeURIComponent(formType)}`,{force:true});return false}
  function successScreen(title,text,nextRoute="home",nextLabel="Към началото",shareNote=false){state.dirty=false;main.innerHTML=pageIntro("Готово",title,text)+`<section class="section"><div class="shell form-wrap"><div class="form-card"><div class="notice notice-ok"><strong>${esc(title)}</strong>${esc(text)}</div>${shareNote?`<div class="notice notice-info mt-12"><strong>Споделяне</strong>След одобрение и създаване на публична страница бутонът „Сподели“ става активен.</div>`:""}<div class="form-actions mt-16"><button class="button button-primary" data-route="${esc(nextRoute)}">${esc(nextLabel)}</button><button class="button button-soft" data-route="profile">Виж профила / статуса</button></div></div></div></section>`;window.scrollTo({top:0,behavior:"smooth"})}
  function submitForm(form){if(!validateForm(form))return;const type=form.dataset.form,fd=new FormData(form);if(["listing","firm","health-proposal","shop-proposal","question","answer","correction","report","offer-request"].includes(type)&&!requireSignIn(type,form))return;state.dirty=false;
    if(type==="home-search"||type==="search"){navigate(`search?q=${encodeURIComponent(fd.get("q")||"")}`,{force:true});return}
    if(type==="login"){state.role="user";saveState();const draft=readPendingDraft();if(draft?.route){navigate(draft.route,{force:true});return}successScreen("Входът е успешен","В прототипа си влязъл като обикновен потребител.","profile","Към профила");refreshRoleUI();return}
    if(type==="register"){state.role="user";saveState();const draft=readPendingDraft();if(draft?.route){navigate(draft.route,{force:true});return}successScreen("Профилът е създаден","Симулация: акаунтът е активен и си влязъл.","profile","Към профила");refreshRoleUI();return}
    if(type==="recover"){successScreen("Инструкциите са изпратени","Симулация: провери електронната си поща за линк за възстановяване.","auth/login","Към вход");return}
    clearPendingDraft();
    if(type==="listing"){const edit=Boolean(form.dataset.editId);state.submissions.push({kind:"listing",status:isAdmin()?"approved":"pending",time:Date.now()});saveState();if(isAdmin())successScreen(edit?"Промените са публикувани":"Обявата е публикувана","Администраторската публикация е показана като публикувана веднага според защитеното правило.","marketplace","Към обявите");else successScreen(edit?"Промените са изпратени за преглед":"Изпратено за преглед",edit?"Редакцията чака одобрение; последната одобрена версия остава публична.":"Обявата няма да е публична преди одобрение.","marketplace","Към обявите",true);return}
    if(type==="firm"){const edit=Boolean(form.dataset.editId);state.submissions.push({kind:"firm",status:isAdmin()?"approved":"pending",time:Date.now()});saveState();successScreen(isAdmin()?(edit?"Фирмата е обновена и публикувана":"Фирмата е публикувана"):(edit?"Редакцията е изпратена за преглед":"Фирмата е изпратена за преглед"),isAdmin()?"Администраторската промяна е показана като публикувана веднага.":"Последната одобрена версия остава публична до одобряване на промяната.","firms","Към фирмите",!isAdmin());return}
    if(type==="health-proposal"){successScreen("Изпратено е за одобрение","Ще се публикува само след преглед.","marketplace/services?group=health","Към Здраве и грижа",true);return}
    if(type==="shop-proposal"){successScreen("Предложението е изпратено за проверка","Магазинът няма да се показва публично преди одобрение.","shops","Към магазините",true);return}
    if(type==="question"){successScreen(isAdmin()?"Въпросът е публикуван":"Въпросът е изпратен за преглед",isAdmin()?"Администраторският въпрос е показан като публикуван веднага.":"След одобрение въпросът ще има публична страница.","questions","Към въпросите",!isAdmin());return}
    if(type==="answer"){successScreen("Отговорът е изпратен за преглед","Ще се появи публично само след одобрение.",`question/${form.dataset.questionId}`,"Към въпроса");return}
    if(type==="correction"){successScreen("Корекцията е изпратена","Публичният запис не е променен директно. Предложението чака проверка.","info","Към Инфо Лом");return}
    if(type==="report"){successScreen("Сигналът е изпратен","Съдържанието не се изтрива автоматично; сигналът влиза за преглед.","home","Към началото");return}
    if(type==="offer-request"){successScreen("Запитването е подготвено","В прототипа няма реално изпращане.","firms","Към фирмите");return}
    if(type==="contact"){successScreen("Съобщението е прието","Това е симулация на контактната форма в прототипа.","home","Към началото");return}
  }
  window.addEventListener("hashchange",()=>setTimeout(restorePendingDraft,0));
