"use strict";
const D = window.POPITAI_PROTO_DATA;
const main = document.getElementById("main");
const addLayer = document.getElementById("add-layer");
const shareLayer = document.getElementById("share-layer");
const confirmLayer = document.getElementById("confirm-layer");
const toastEl = document.getElementById("toast");
const STORAGE = "popitai_v6_full_proto_r1";
const state = Object.assign({role:"guest",dataState:"loaded",profileTab:"summary",adminTab:"dashboard",submissions:[],dirty:false,lastFocus:null}, readState());
let toastTimer = null;

function readState(){try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")||{}}catch{return {}}}
function saveState(){const safe={role:state.role,dataState:state.dataState,profileTab:state.profileTab,adminTab:state.adminTab,submissions:state.submissions};localStorage.setItem(STORAGE,JSON.stringify(safe))}
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=v=>esc(v).replace(/\n/g,"<br>");
const signedIn=()=>state.role!=="guest";
const isAdmin=()=>state.role==="admin";
const isModerator=()=>state.role==="moderator";
const ownLabel=()=>isAdmin()?"Администратор":isModerator()?"Модератор":"Потребител";
function toast(message){clearTimeout(toastTimer);toastEl.textContent=message;toastEl.hidden=false;toastTimer=setTimeout(()=>toastEl.hidden=true,2600)}
function routeInfo(){const raw=(location.hash||"#/home").replace(/^#\/?/,"");const [path,q=""]=raw.split("?");return {raw,path:path||"home",parts:(path||"home").split("/").filter(Boolean),params:new URLSearchParams(q)}}
function routeUrl(route){return `#/${route}`}
function navigate(route,{force=false}={}){if(state.dirty&&!force&&!window.confirm("Има неизпратени данни. Да напусна ли формата?"))return;state.dirty=false;closeAllModals();if(location.hash===routeUrl(route)){render()}else location.hash=routeUrl(route)}
function crumb(items){return `<nav class="breadcrumbs" aria-label="Навигационна пътека">${items.map((x,i)=>i===items.length-1?`<span>${esc(x[0])}</span>`:`<button type="button" data-route="${esc(x[1])}">${esc(x[0])}</button>`).join("")}</nav>`}
function pageIntro(kicker,title,text,actions=""){return `<section class="page-intro"><div class="shell">${kicker?`<span class="eyebrow">${esc(kicker)}</span>`:""}<div class="section-head"><div><h1>${esc(title)}</h1>${text?`<p>${esc(text)}</p>`:""}</div>${actions?`<div class="section-actions">${actions}</div>`:""}</div></div></section>`}
function button(label,route,cls="button button-soft"){return `<button type="button" class="${cls}" data-route="${esc(route)}">${esc(label)}</button>`}
function statusBadge(status){const map={approved:["Публикувано","badge-ok"],pending:["Чака преглед","badge-warn"],needs_changes:["За корекция","badge-danger"],rejected:["Отказано","badge-danger"],confirmed:["Потвърдено","badge-ok"],"prototype-only":["Временна услуга","badge-blue"]};const x=map[status]||[status,"badge"];return `<span class="badge ${x[1]}">${esc(x[0])}</span>`}
function stateGate(loadedHtml,emptyText="Няма съдържание за показване."){
  if(state.dataState==="loaded")return loadedHtml;
  if(state.dataState==="loading")return `<div class="result-list"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>`;
  if(state.dataState==="empty")return `<div class="empty-state"><h2>Все още няма резултати</h2><p>${esc(emptyText)}</p></div>`;
  if(state.dataState==="offline")return `<div class="system-state"><h2>Няма връзка</h2><p>Провери интернет връзката. Въведените данни във формите не се изтриват.</p><button class="button button-soft" type="button" data-action="retry">Опитай отново</button></div>`;
  if(state.dataState==="partial")return `<div class="notice notice-warn"><strong>Частичен резултат</strong>Един от източниците не отговори, затова показваме наличното, без да твърдим, че няма други резултати. <button class="button button-soft mt-12" type="button" data-action="retry">Опитай отново</button></div>${loadedHtml}`;
  if(state.dataState==="cancelled")return `<div class="notice notice-info"><strong>По-нова заявка е активна</strong>По-старото търсене е отменено и няма да презапише по-новия резултат.</div>`;
  return `<div class="system-state"><h2>Не успяхме да заредим съдържанието</h2><p>Това е отделно състояние при грешка. Не го представяме като „няма резултат“.</p><button class="button button-soft" type="button" data-action="retry">Опитай отново</button></div>`;
}
function categoryCard(x,route){return `<button class="card category-card" type="button" data-route="${esc(route)}"><span class="category-icon" aria-hidden="true">${esc(x.icon||"•")}</span><h3>${esc(x.title)}</h3><p>${esc(x.text||"")}</p><span class="card-foot">Разгледай →</span></button>`}
function listingSort(rows){return [...rows].sort((a,b)=>(Number(b.admin)-Number(a.admin))||(Number(b.boosted)-Number(a.boosted))||a.title.localeCompare(b.title,"bg"))}
function listingCard(l){return `<article class="result-card"><div><span class="owner-label">${l.ownerType==="firm"?"Фирмена обява":"Обява"}</span><h3>${esc(l.title)}</h3><p>${esc(l.description)}</p><div class="result-meta">${statusBadge(l.status)}<span>${esc(l.type)}</span><span>${esc(l.city)}</span>${l.subcategory?`<span>${esc(publicSubcategory(l.subcategory))}</span>`:""}${l.admin?`<span class="badge badge-dark">Администраторски приоритет след релевантност</span>`:""}</div></div><div class="result-actions"><span class="price">${esc(l.price||"")}</span><button class="button button-soft" type="button" data-route="listing/${esc(l.id)}">Виж обявата</button></div></article>`}
function publicSubcategory(stored){const aliases={"Красота и грижа":"Красота и лична грижа","Фото, видео и събитийни услуги":"Фото и видео услуги","Транспорт, преместване и доставки":"Транспорт и доставки"};return aliases[stored]||stored}
function listingBrowse({title,text,rows,baseRoute,showFilters=true}){
  const r=routeInfo();const mode=r.params.get("show")||"all";let filtered=rows;
  if(mode==="offer")filtered=filtered.filter(x=>/Предлага|Продава|Отдава|Дава/.test(x.type));
  if(mode==="seek")filtered=filtered.filter(x=>/Търси|Купува/.test(x.type));
  if(mode==="firms")filtered=filtered.filter(x=>x.ownerType==="firm");
  const filterUI=showFilters?`<div class="toolbar"><div class="segmented"><button class="${mode==="all"?"active":""}" data-filter-route="${esc(baseRoute)}" data-filter="all">Всички</button><button class="${mode==="offer"?"active":""}" data-filter-route="${esc(baseRoute)}" data-filter="offer">Предлагат</button><button class="${mode==="seek"?"active":""}" data-filter-route="${esc(baseRoute)}" data-filter="seek">Търсят</button><button class="${mode==="firms"?"active":""}" data-filter-route="${esc(baseRoute)}" data-filter="firms">Фирми</button></div><button class="button button-primary" type="button" data-route="listing-form?from=${encodeURIComponent(baseRoute)}">Добави обява</button></div>`:"";
  return `<div class="section-head"><div><h2>${esc(title)}</h2><p>${esc(text)}</p></div></div>${filterUI}${stateGate(filtered.length?`<div class="result-list">${listingSort(filtered).map(listingCard).join("")}</div>`:`<div class="empty-state"><h2>Няма резултати с този филтър</h2><p>Промени филтъра или публикувай подходяща обява.</p>${button("Добави обява","listing-form","button button-primary")}</div>`,"За тази селекция още няма обяви.")}`
}

function renderHome(){
  const infoCards=D.infoFamilies.map(x=>categoryCard(x,`info/${x.key}`)).join("");
  const discover=[{icon:"▦",title:"Магазини",text:"Местни магазини и какво предлагат.",route:"shops"},{icon:"☰",title:"Заведения",text:"Ресторанти и места за храна.",route:"restaurants"},{icon:"▣",title:"Фирми",text:"Постоянни профили на местни доставчици.",route:"firms"},{icon:"○",title:"Събития",text:"Какво предстои в Лом.",route:"events"}];
  main.innerHTML=`<section class="hero"><div class="hero-inner"><div><span class="eyebrow">Местното място за Лом</span><h1>Намери човек, услуга, обява или проверена информация.</h1><p>Един ясен вход към местните услуги, работа, имоти, фирми, препоръки и Инфо Лом.</p><form class="search-bar" data-form="home-search"><input name="q" aria-label="Търсене" placeholder="Какво търсиш в Лом?" autocomplete="off"><button class="button button-primary" type="submit">Търси</button></form></div><aside class="hero-aside"><h2>Бързи действия</h2><div class="hero-mini"><button data-route="marketplace"><strong>Разгледай обяви и услуги</strong><small>Услуги, автомобили, работа, имоти и стоки</small></button><button data-route="info"><strong>Инфо Лом</strong><small>Проверени местни контакти и информация</small></button><button data-route="questions"><strong>Попитай общността</strong><small>Съвети, опит и препоръки</small></button></div></aside></div></section>
    <section class="section"><div class="shell"><div class="section-head"><div><h2>Обяви и услуги</h2><p>Пет ясни входа — без „други услуги“ и „други обяви“.</p></div>${button("Всички обяви","marketplace")}</div><div class="grid grid-5">${D.marketplace.map(x=>categoryCard(x,`marketplace/${x.key}`)).join("")}</div></div></section>
    <section class="section section-tight"><div class="shell"><div class="section-head"><div><h2>Открий в Лом</h2><p>Постоянни места, фирми и местни събития.</p></div></div><div class="grid grid-4">${discover.map(x=>categoryCard(x,x.route)).join("")}</div></div></section>
    <section class="section"><div class="shell"><div class="section-head"><div><h2>Проверена информация</h2><p>Шестте основни раздела на Инфо Лом.</p></div>${button("Инфо Лом","info")}</div><div class="grid grid-3">${infoCards}</div></div></section>
    <section class="section section-tight"><div class="shell"><div class="section-head"><div><h2>Полезни ръководства</h2><p>Практични насоки, без да копират променливите факти от Инфо Лом.</p></div>${button("Всички статии","articles")}</div><div class="grid grid-3">${D.articles.slice(0,3).map(articleCard).join("")}</div></div></section>
    <section class="section"><div class="shell"><div class="section-head"><div><h2>Въпроси и препоръки</h2><p>Когато търсиш опит от хората в Лом.</p></div>${button("Задай въпрос","ask","button button-primary")}</div><div class="grid grid-2">${D.questions.slice(0,2).map(questionCard).join("")}</div></div></section>`;
}

function renderMarketplace(){
  const r=routeInfo();const key=r.parts[1];
  if(!key){main.innerHTML=pageIntro("Намери или публикувай","Обяви и услуги","Избери какво търсиш. Картите водят към разглеждане; добавянето е отделно действие.",button("Добави обява","listing-form","button button-primary"))+`<section class="section"><div class="shell"><div class="grid grid-5">${D.marketplace.map(x=>categoryCard(x,`marketplace/${x.key}`)).join("")}</div><div class="notice notice-info mt-16"><strong>Как работи</strong>Избираш раздел → разглеждаш резултати → при нужда натискаш отделното „Добави обява“. Въпросите са вторично действие, а не заместител на обявите.</div></div></section>`;return}
  if(key==="services")return renderServices();
  if(key==="vehicles")return renderVehicles();
  if(key==="work")return renderWork();
  if(key==="property")return renderProperty();
  if(key==="trade")return renderTrade();
  renderNotFound();
}
function renderServices(){
  const r=routeInfo();const group=r.params.get("group");const leaf=r.params.get("leaf");
  if(group==="health")return renderHealth();
  if(group){const g=D.serviceGroups.find(x=>x.key===group);if(!g)return renderNotFound();const rows=D.listings.filter(x=>x.main==="services"&&x.group===group&&(!leaf||publicSubcategory(x.subcategory)===leaf||x.subcategory===leaf));main.innerHTML=pageIntro("Услуги",leaf||g.title,leaf?`Обяви и доставчици за „${leaf}“.`:g.text,button("Добави обява",`listing-form?main=services&group=${group}${leaf?`&leaf=${encodeURIComponent(leaf)}`:""}`,"button button-primary")+button("Попитай",`ask?category=${encodeURIComponent(g.title)}`))+`<section class="section"><div class="shell">${crumb([["Обяви и услуги","marketplace"],["Услуги","marketplace/services"],[g.title,`marketplace/services?group=${group}`],...(leaf?[[leaf,""]]:[])])}${!leaf?`<div class="grid grid-4">${g.leaves.map(l=>categoryCard({icon:g.icon,title:l,text:"Разгледай предложения и търсения."},`marketplace/services?group=${group}&leaf=${encodeURIComponent(l)}`)).join("")}</div><div class="divider"></div>`:""}${listingBrowse({title:leaf||g.title,text:"Тук се показват временните обяви за услуги; постоянните фирмени профили остават отделен тип съдържание.",rows,baseRoute:`marketplace/services?group=${group}${leaf?`&leaf=${encodeURIComponent(leaf)}`:""}`})}</div></section>`;return}
  main.innerHTML=pageIntro("Обяви и услуги","Услуги","Осем ясни групи. Избери тема, после конкретна услуга.",button("Добави обява","listing-form?main=services","button button-primary"))+`<section class="section"><div class="shell">${crumb([["Обяви и услуги","marketplace"],["Услуги",""]])}<div class="grid grid-4">${D.serviceGroups.map(g=>categoryCard(g,`marketplace/services?group=${g.key}`)).join("")}</div><div class="divider"></div>${listingBrowse({title:"Последни услуги",text:"Релевантни предложения и търсения.",rows:D.listings.filter(x=>x.main==="services"),baseRoute:"marketplace/services"})}</div></section>`;
}
function renderVehicles(){const r=routeInfo(),leaf=r.params.get("leaf");const rows=D.listings.filter(x=>x.main==="vehicles"&&(!leaf||(leaf==="Автомобили за продажба или търсене"?!x.subcategory:publicSubcategory(x.subcategory)===leaf)));main.innerHTML=pageIntro("Обяви и услуги","Автомобили","Автомобили за купуване/продажба и автомобилни услуги.",button("Добави обява",`listing-form?main=vehicles${leaf?`&leaf=${encodeURIComponent(leaf)}`:""}`,"button button-primary"))+`<section class="section"><div class="shell">${crumb([["Обяви и услуги","marketplace"],["Автомобили",""]])}<div class="grid grid-4">${D.autoLeaves.map(l=>categoryCard({icon:"▱",title:l,text:"Разгледай обяви и услуги."},`marketplace/vehicles?leaf=${encodeURIComponent(l)}`)).join("")}</div><div class="divider"></div>${listingBrowse({title:leaf||"Автомобили",text:"„Продава/Купува“ е за автомобили, а „Предлага/Търси“ — за автомобилните услуги.",rows,baseRoute:`marketplace/vehicles${leaf?`?leaf=${encodeURIComponent(leaf)}`:""}`})}</div></section>`}
function renderWork(){const rows=D.listings.filter(x=>x.main==="work");main.innerHTML=pageIntro("Обяви и услуги","Работа","Отделен ясен вход за работодатели и хора, които търсят работа.",button("Добави обява","listing-form?main=work","button button-primary")+button("Попитай за работа","ask?category=Работа"))+`<section class="section"><div class="shell">${crumb([["Обяви и услуги","marketplace"],["Работа",""]])}${listingBrowse({title:"Работа в Лом и района",text:"Избираш ясно дали предлагаш работа или търсиш работа.",rows,baseRoute:"marketplace/work",showFilters:false})}</div></section>`}
function renderProperty(){const rows=D.listings.filter(x=>x.main==="property");main.innerHTML=pageIntro("Обяви и услуги","Имоти","Продажба, отдаване и търсене на имоти без излишни допълнителни категории.",button("Добави обява","listing-form?main=property","button button-primary"))+`<section class="section"><div class="shell">${crumb([["Обяви и услуги","marketplace"],["Имоти",""]])}<div class="tag-row"><span class="badge badge-blue">Продава имот</span><span class="badge badge-blue">Отдава под наем</span><span class="badge badge-blue">Търси под наем</span><span class="badge badge-blue">Търси за купуване</span></div><div class="divider"></div>${listingBrowse({title:"Имоти в Лом и района",text:"Показват се обявите за продажба, отдаване и търсене на имоти.",rows,baseRoute:"marketplace/property",showFilters:false})}</div></section>`}
function renderTrade(){const r=routeInfo(),leaf=r.params.get("leaf");const rows=D.listings.filter(x=>x.main==="trade"&&(!leaf||x.category===leaf));main.innerHTML=pageIntro("Обяви и услуги","Купува и продава","Стоки в седем ясни категории. Работа, Имоти и Автомобили не се дублират тук.",button("Добави обява",`listing-form?main=trade${leaf?`&leaf=${encodeURIComponent(leaf)}`:""}`,"button button-primary"))+`<section class="section"><div class="shell">${crumb([["Обяви и услуги","marketplace"],["Купува и продава",""]])}<div class="grid grid-4">${D.tradeLeaves.map(l=>categoryCard({icon:"⇄",title:l,text:"Купувай, продавай, търси или подарявай."},`marketplace/trade?leaf=${encodeURIComponent(l)}`)).join("")}</div><div class="divider"></div>${listingBrowse({title:leaf||"Купува и продава",text:"Една обява се публикува веднъж и се показва на подходящите места.",rows,baseRoute:`marketplace/trade${leaf?`?leaf=${encodeURIComponent(leaf)}`:""}`})}</div></section>`}
